### ISSUE TITLE
Exception: No such file or directory - bundle install

### ISSUE THREAD

**Issue by kevin-marshall** [dev-gem/dev#4]
I am trying to rake a project which has a Gemfile in the root directory.

To get the exception I uninstall the dev gem and I uninstall bundler. I then install the dev gem. Now I rake the project and the exception occurs.

I am speculating that the bundler gem is not getting installed with the dev gem, but the dev gem does invoke "bundler install" in the setup task if a Gemfile file is present.

I am guessing to fix the issue the bundler gem needs to be added to the dev.gemspec file.

**Comment by lou-parslow** [comment]
fixed
