### ISSUE TITLE
Recent change causing me some problems.

### ISSUE THREAD

**Issue by kevin-marshall** [dev-gem/dev#5]
![image](https://user-images.githubusercontent.com/6132885/61011058-12c56a80-a336-11e9-8d57-88f6fb27bad0.png)

Project names which have a space in them are now causing issues. Can you add " around the sln_filename to manage the space in the file name.

			Dir.glob('**/*.sln').each{|sln_file|
				add_quiet "nuget restore \"#{sln_file}\"" if(!sln_file.include?('packages/'))
			}
		else
			Dir.glob('**/*.sln').each{|sln_file|
				add_quiet "dotnet restore \"#{sln_file}\""
			}
		end

**Comment by lou-parslow** [comment]
fixed
